/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************/

#include "stm32f103c6.h"
#include "GPIO.h"
#include "LCD.h"
#include "EXTRI_Driver.h"


uint8_t flag  =1;
void delay(int x)
{
	for(int i =0 ;i<x; i++)
	{
		for(int j =0 ; j <255 ; j++);

	}
}
void CLOCK_init()
{
	//enable clock to GPIOB , GPIOA , AFIO
	RCC_GPIOA_CLK_EN();
	RCC_GPIOB_CLK_EN();
	RCC_AFIO_CLK_EN();
}

void EXTI_DisplayMessage()
{
	flag = 0;
	char str []= "HI,FROM EXTI ISR";
	LCD_WRITE_STRING(str);

	delay(1000);
}

int main(void)
{
	CLOCK_init();
	LCD_INIT();
	char str1 []= "HI, Kyrillos";
	LCD_WRITE_STRING(str1);
	delay(1000);
	LCD_clear_screen();

	EXTI_PinConfig_t  EXTI_Config ;

	EXTI_Config.EXTI_PIN = EXTI9PB9;
	EXTI_Config.Triger_Case = EXTI_TRAGGER_RISSING_EDGE;
	EXTI_Config.P_IRQ_CallBack = EXTI_DisplayMessage;
	EXTI_Config.IRQ_Enable = EXTI_IRQ_ENABLE;


	MCAL_EXTI_GPIO_Init(&EXTI_Config);

	while(1)
	{
		if(!flag)
		{
			LCD_clear_screen();
			flag =1;
		}
	}
}
