/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 */

#include "USART.h"
#include "GPIO.h"
#include "RCC.h"
#include "stm32f103c6.h"


uint16_t Data ;

void clock_init()
{
	RCC_GPIOA_CLK_EN();
	RCC_GPIOB_CLK_EN();
	RCC_AFIO_CLK_EN();
}

//void USART_IRQ_CallBack(void) {
//
//	MCAL_UART_ReceiveData(USART1, &Data ,disable);
//
//	MCAL_UART_SendData(USART1, &Data ,enable);
//}

void delay(int x)
{
	for (int i = 0 ;i<x;i++)
		for(int j =0 ;j<255;j++);
}


int main(void) {

	clock_init();
	delay(25);

	USART_Config Uart1_Parameters;
	Uart1_Parameters.UART_MODE     = UART_MODE_TX_RX;
	Uart1_Parameters.Payload_Length = UART_Payload_Length_8B;
	Uart1_Parameters.Parity         = UART_Parity_NONE;
	Uart1_Parameters.StopBits       = UART_StopBits_1;
	Uart1_Parameters.BaudRate       = UART_BaudRate_115200;
	Uart1_Parameters.HwFlowCtl      = UART_HwFlowCtl_NONE;
	Uart1_Parameters.IRQ_Enable	 = UART_IRQ_Enable_NONE;
	//Uart1_Parameters.P_IRQ_CallBack = USART_IRQ_CallBack;
	Uart1_Parameters.P_IRQ_CallBack = 0;
	MCAL_UART_Init(USART1,&Uart1_Parameters);
	MCAL_UART_GPIO_Set_Pins(USART1);




	while(1)
	{
		MCAL_UART_ReceiveData(USART1, &Data ,enable);

		MCAL_UART_SendData(USART1, &Data ,enable);
	}


}


